#!/bin/bash

coverage() {

	echo -e "\t\t++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> testresults.out
	echo -e "\t\t++                                                                  ++" >> testresults.out
	if [[ $1 = "randomtest_adventurer" ]] ; then
		echo -e "\t\t++          \t\t      ${programName}                     ++" >> testresults.out
	else
		echo -e "\t\t++          \t         ${programName}                     ++" >> testresults.out
	fi
	echo -e "\t\t++                                                                  ++" >> testresults.out
	echo -e "\t\t++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> testresults.out

	echo -e "\t  Result for running ${programName} (${test}):" >> testresults.out
	echo -e "\t\t\t\t\t\t\t\t  ${programName}:" >> testresults.out 
	./"${programName}" >> testresults.out

	echo -e "\t  Coverage Report:\n" >> testresults.out
	printf "\t" >> testresults.out
	line=$(gcov ${gcovProg} --function-summaries -b | grep -n ${funcName} | cut -f1 -d:)
	((line+=3))
	gcov ${gcovProg} --function-summaries -b | head -n${line} | tail -n4 >> testresults.out
		
	for i in "${!ancillary_functs[@]}" ; do
		echo >> testresults.out
		if [[ ${i} = 0 ]] ; then
			echo -e "The following functions are called by ${funcName}...\n" >> testresults.out
		fi
		printf "\t" >> testresults.out
		line=$(gcov dominion.c --function-summaries -b | grep -n ${ancillary_functs[$i]} | cut -f1 -d:)
		((line+=3))
		gcov dominion.c --function-summaries -b | head -n${line} | tail -n4 >> testresults.out
	done
	
	echo -e "\n\n --------------------------------- END RANDOM TEST ${testNumber} -----------------------------\n\n" >> testresults.out
}

gcovProg="dominion.c"
programName=$1
testNumber=$2

if [[ $1 = "randomtest_councilroom" ]] ; then 
	test="random tests for Council Room"
	funcName="playCouncilRoom"
	ancillary_functs[0]="drawCard"
	ancillary_functs[1]="discardCard"
else 
	test="random tests for Adventurer"
	funcName="playAdventurer"
	ancillary_functs[0]="drawCard"
fi

coverage $1

## REFERENCES
# https://stackoverflow.com/questions/6723426/looping-over-arrays-printing-both-index-and-value
# Shotts, William E., The Linux Command Line. http://linuxcommand.org/tlcl.php



