#!/bin/bash

echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" > unittestresults.out
echo "++                                                                  ++" >> unittestresults.out
echo "++                           UNIT TEST 1                            ++" >> unittestresults.out
echo "++                                                                  ++" >> unittestresults.out
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> unittestresults.out

echo "Result for running unittest1 (gainCard function test):" >> unittestresults.out
echo "unittest1.c:" >> unittestresults.out
./unittest1 >> unittestresults.out
line=$(gcov dominion.c --function-summaries | grep -n gainCard | cut -f1 -d:)
((line++))
gcov dominion.c --function-summaries | head -n$(echo $line) | tail -n2 >> unittestresults.out

echo -e "\n\n" >> unittestresults.out



echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> unittestresults.out
echo "++                                                                  ++" >> unittestresults.out
echo "++                           UNIT TEST 2                            ++" >> unittestresults.out
echo "++                                                                  ++" >> unittestresults.out
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> unittestresults.out

echo "Result for running unittest2 (buyCard function test):" >> unittestresults.out
echo "unittest2.c:" >> unittestresults.out
./unittest2 >> unittestresults.out
line=$(gcov dominion.c --function-summaries | grep -n buyCard | cut -f1 -d:)
((line++))
gcov dominion.c --function-summaries | head -n$(echo $line) | tail -n2 >> unittestresults.out

echo -e "\n\tThe following functions are called by buyCard...\n" >> unittestresults.out
line=$(gcov dominion.c --function-summaries | grep -n gainCard | cut -f1 -d:)
((line++))
gcov dominion.c --function-summaries | head -n$(echo $line) | tail -n2 >> unittestresults.out

echo -e "\n\n" >> unittestresults.out



echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> unittestresults.out
echo "++                                                                  ++" >> unittestresults.out
echo "++                           UNIT TEST 3                            ++" >> unittestresults.out
echo "++                                                                  ++" >> unittestresults.out
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> unittestresults.out

echo "Result for running unittest3 (shuffle function test):" >> unittestresults.out
echo "unittest3.c:" >> unittestresults.out
./unittest3 >> unittestresults.out
line=$(gcov dominion.c --function-summaries | grep -n shuffle | cut -f1 -d:)
((line++))
gcov dominion.c --function-summaries | head -n$(echo $line) | tail -n2 >> unittestresults.out

echo -e "\n\n" >> unittestresults.out



echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> unittestresults.out
echo "++                                                                  ++" >> unittestresults.out
echo "++                           UNIT TEST 4                            ++" >> unittestresults.out
echo "++                                                                  ++" >> unittestresults.out
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> unittestresults.out

echo "Result for running unittest4 (updateCoins function test):" >> unittestresults.out
echo "unittest4.c:" >> unittestresults.out
./unittest4 >> unittestresults.out
line=$(gcov dominion.c --function-summaries | grep -n updateCoins | cut -f1 -d:)
((line++))
gcov dominion.c --function-summaries | head -n$(echo $line) | tail -n2 >> unittestresults.out